name: "Github Action Secrets Sync"

on:
  push:
    branches:
      - main

jobs:
  secrets-sync:
    runs-on: ubuntu-latest

    steps:
      - run: env

      - name: secrets sync
        uses: jpoehnelt/secrets-sync-action@v1.10.0
        with:
          github_token: ${{ secrets.MY_GITHUB_TOKEN }}
          repositories: |
            subchen/java-formatter-maven-plugin
            subchen/jetbrick-template-2x
          secrets: |
            MY_GITHUB_TOKEN
            MAVEN_DEPLOY_USERNAME
            MAVEN_DEPLOY_PASSWORD
            GPG_PRIVATE_KEY
            GPG_PASSPHRASE
